"""fixed an issue on the department model

Revision ID: 64b69f93052c
Revises: 8f7f5a0a1930
Create Date: 2025-12-24 12:46:06.258867

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '64b69f93052c'
down_revision = '8f7f5a0a1930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('address', sa.Integer(), nullable=True))
    op.drop_column('department', 'salary')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('department', sa.Column('salary', sa.INTEGER(), nullable=True))
    op.drop_column('department', 'address')
    # ### end Alembic commands ###
